import {test} from 'node:test';import assert from 'node:assert/strict';import {readdirSync,readFileSync} from 'node:fs';import {resolve} from 'node:path';
const dir=readdirSync('node_modules/.pnpm').find(x=>x.startsWith('miniflare@'));const {Miniflare}=await import(resolve('node_modules/.pnpm',dir,'node_modules/miniflare/dist/src/index.js'));
const kind=readFileSync('lib/config.ts','utf8').match(/KIND:string='([^']+)'/)[1];
const files=readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0);const mf=new Miniflare({modules:files.map(path=>({type:'ESModule',path:resolve('dist/server',path),contents:readFileSync('dist/server/'+path,'utf8')})),modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}});
const db=await mf.getD1Database('DB');const migration=readdirSync('drizzle').find(x=>x.endsWith('.sql'));await db.exec(readFileSync('drizzle/'+migration,'utf8').replaceAll('\n',' '));
const get=async()=>{const r=await mf.dispatchFetch('https://test.local/api/state');assert.equal(r.status,200);return await r.json()};
const post=async(body,origin='https://test.local')=>{const r=await mf.dispatchFetch('https://test.local/api/state',{method:'POST',headers:{origin,'content-type':'application/json','x-workbench-request':'1'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}};
try{
 await test('API initialization and repeat read preserve revision',async()=>{const s=await get();assert.equal(s.kind,kind);assert.equal((await get()).version,s.version)});
 await test('cross-origin write rejected',async()=>{const s=await get();assert.equal((await post({action:'invalid',version:s.version},'https://other.local')).status,403)});
 await test('invalid action returns validation failure',async()=>{const s=await get();assert.equal((await post({action:'invalid',version:s.version})).status,400)});
 if(kind==='accessgraph'){
 const profile={maxSlope:5,minWidth:120,allowSteps:false,freshDays:30,excludeStale:false};
 await test('API route calculation and snapshot persist',async()=>{const s=await get();const p=await post({action:'route',version:s.version,start:'n1',end:'n4',profile});assert.equal(p.status,200);assert.equal(p.data.result.meters,590);const save=await post({action:'save-route',version:s.version,start:'n1',end:'n4',profile});assert.equal(save.status,200);assert.equal((await get()).saved.length,1);assert.equal((await post({action:'save-route',version:s.version,start:'n1',end:'n4',profile})).status,409)});
 await test('simultaneous audits have one winner and one conflict',async()=>{const s=await get();const body={action:'audit',version:s.version,linkId:'e1',slope:3,width:150,steps:false,closed:false,note:'Measured in integration test'};const r=await Promise.all([post(body),post(body)]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);const next=await get();assert.equal(next.audits.length,1);assert.equal(next.links.find(l=>l.id==='e1').width,150)})
 }else{
 const parameters={item:kind==='reliefledger'?'Food packs':'Timber',capacity:20,maxDistance:15,payloadKg:650,transportRate:15};let planId;
 await test('simultaneous reservations only commit once',async()=>{const s=await get();const r=await Promise.all([post({action:'reserve',version:s.version,id:crypto.randomUUID(),parameters}),post({action:'reserve',version:s.version,id:crypto.randomUUID(),parameters})]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);const next=await get();assert.equal(next.plans.length,1);assert.equal(next.stock.reduce((a,x)=>a+x.reserved,0),20);planId=next.plans[0].id});
 await test('retry with same id cannot reserve stock twice',async()=>{const s=await get();const r=await post({action:'reserve',version:s.version,id:planId,parameters});assert.equal(r.status,200);assert.equal((await get()).stock.reduce((a,x)=>a+x.reserved,0),20)});
 await test('cancellation restores stock and duplicate cancellation is safe',async()=>{let s=await get();const original=s.stock.reduce((a,x)=>a+x.available+x.reserved,0);assert.equal((await post({action:'settle',version:s.version,id:planId,status:'CANCELLED'})).status,200);s=await get();assert.equal(s.stock.reduce((a,x)=>a+x.available,0),original);assert.equal(s.stock.reduce((a,x)=>a+x.reserved,0),0);assert.equal((await post({action:'settle',version:s.version,id:planId,status:'CANCELLED'})).status,200);assert.equal((await post({action:'settle',version:s.version,id:planId,status:'DELIVERED'})).status,409)});
 await test('record creation and preview read back persisted data',async()=>{const s=await get();const r=await post({action:'add-request',version:s.version,name:'Test community',item:parameters.item,x:3,y:2,grade:'A',lengthMm:2200,quantity:10,priority:3,maxPrice:50000,dueAt:new Date(Date.now()+86400000).toISOString()});assert.equal(r.status,200);const next=await get();assert(next.requests.some(x=>x.name==='Test community'));const preview=await post({action:'preview',version:next.version,parameters});assert.equal(preview.status,200);assert(preview.data.result.total>0)})
 }
 await test('built root renders branded HTML',async()=>{const r=await mf.dispatchFetch('https://test.local/');assert.equal(r.status,200);const html=await r.text();assert(html.includes('Fictional data'));assert(html.includes('Private demonstration workspace'))});
}finally{await mf.dispose()}
