export type RecordData = {id:string;name:string;[key:string]:any};
export function route(nodes:RecordData[],links:RecordData[],start:string,end:string,p:any,now=Date.now()){
 if(!nodes.some(n=>n.id===start)||!nodes.some(n=>n.id===end))throw new Error('Unknown route endpoint');
 const blocked:any[]=[];const valid=links.filter(l=>{const why=[];if(l.closed)why.push('Closed');if(l.steps&&!p.allowSteps)why.push('Steps');if(l.slope>p.maxSlope)why.push('Slope exceeds limit');if(l.width<p.minWidth)why.push('Too narrow');if(p.excludeStale&&(now-Date.parse(l.auditedAt))/86400000>p.freshDays)why.push('Audit too old');if(!(l.length>0))throw new Error('Invalid link length');if(why.length)blocked.push({id:l.id,why});return !why.length});
 const d:Record<string,number>={};const prev:Record<string,any>={};const remaining=new Set(nodes.map(n=>n.id));nodes.forEach(n=>d[n.id]=Infinity);d[start]=0;
 while(remaining.size){let u=[...remaining].sort((a,b)=>d[a]-d[b])[0];if(d[u]===Infinity)break;remaining.delete(u);if(u===end)break;for(const l of valid){let v=l.fromId===u?l.toId:l.toId===u?l.fromId:null;if(!v||!remaining.has(v))continue;const age=Math.max(0,(now-Date.parse(l.auditedAt))/86400000);const score=d[u]+l.length*(1+Math.min(age/p.freshDays,4)*.15);if(score<d[v]){d[v]=score;prev[v]={u,l}}}}
 const path:any[]=[];const nodeIds=[end];if(d[end]!==Infinity){let cur=end;while(cur!==start){path.unshift(prev[cur].l);cur=prev[cur].u;nodeIds.unshift(cur)}}
 return {found:d[end]!==Infinity,path,nodeIds:d[end]===Infinity?[]:nodeIds,meters:path.reduce((a,l)=>a+l.length,0),blocked,stale:path.filter(l=>(now-Date.parse(l.auditedAt))/86400000>p.freshDays).length};
}
export function flow(n:number,source:number,sink:number,arcs:any[],limit:number){
 const graph:any[][]=Array.from({length:n},()=>[]);const tagged:any[]=[];
 for(const a of arcs){if(!Number.isInteger(a.capacity)||a.capacity<0||!Number.isFinite(a.cost))throw new Error('Invalid flow edge');const f={to:a.to,cap:a.capacity,original:a.capacity,cost:a.cost,rev:graph[a.to].length,tag:a.tag};const r={to:a.from,cap:0,cost:-a.cost,rev:graph[a.from].length};graph[a.from].push(f);graph[a.to].push(r);if(a.tag)tagged.push(f)}
 let sent=0,cost=0;while(sent<limit){const dist=Array(n).fill(Infinity),prev:any[]=Array(n);dist[source]=0;const queue=[source],inQ=new Set([source]);while(queue.length){const u=queue.shift()!;inQ.delete(u);graph[u].forEach((a,i)=>{if(a.cap>0&&dist[u]+a.cost<dist[a.to]){dist[a.to]=dist[u]+a.cost;prev[a.to]=[u,i];if(!inQ.has(a.to)){queue.push(a.to);inQ.add(a.to)}}})}if(dist[sink]===Infinity)break;let qty=limit-sent;for(let v=sink;v!==source;v=prev[v][0])qty=Math.min(qty,graph[prev[v][0]][prev[v][1]].cap);for(let v=sink;v!==source;v=prev[v][0]){const a=graph[prev[v][0]][prev[v][1]];a.cap-=qty;graph[v][a.rev].cap+=qty}sent+=qty;cost+=qty*dist[sink]}
 return {sent,cost,lines:tagged.filter(a=>a.original>a.cap).map(a=>({tag:a.tag,quantity:a.original-a.cap}))};
}
export function allocate(stock:RecordData[],requests:RecordData[],p:any,kind:string,now=Date.now()){
 const supplies=stock.filter(s=>s.item===p.item&&s.available>0&&Date.parse(s.expiresAt)>now&&(kind==='reliefledger'||s.verified));
 const needs=requests.filter(r=>r.item===p.item&&r.quantity-r.served-r.reserved>0&&(kind==='reliefledger'||Date.parse(r.dueAt)>now));
 const cap=kind==='reliefledger'?p.capacity:Math.min(p.capacity,Math.floor(p.payloadKg/Math.max(1,...supplies.map(s=>s.weightKg))));
 const sink=2+supplies.length+needs.length;const arcs:any[]=[{from:0,to:1,capacity:cap,cost:0}];const details:Record<string,any>={};let excluded=0;
 supplies.forEach((s,i)=>{arcs.push({from:1,to:2+i,capacity:s.available,cost:0});needs.forEach((r,j)=>{const km=Math.hypot(s.x-r.x,s.y-r.y);const unitPrice=s.unitPrice+Math.round(km*s.weightKg*p.transportRate);const rank:any={A:3,B:2,C:1};if(km>p.maxDistance||(kind!=='reliefledger'&&(rank[s.grade]<rank[r.grade]||s.lengthMm<r.lengthMm||unitPrice>r.maxPrice))){excluded++;return}const tag=s.id+'|'+r.id;details[tag]={stockId:s.id,requestId:r.id,source:s.name,destination:r.name,km:Math.round(km*10)/10,unitPrice,weightKg:s.weightKg};arcs.push({from:2+i,to:2+supplies.length+j,capacity:Math.min(s.available,r.quantity-r.served-r.reserved),cost:kind==='reliefledger'?Math.round(km*10):unitPrice,tag})})});
 needs.forEach((r,j)=>{const remaining=Math.min(cap,r.quantity-r.served-r.reserved);if(kind==='reliefledger'){for(let k=1;k<=remaining;k++)arcs.push({from:2+supplies.length+j,to:sink,capacity:1,cost:Math.round((r.served+r.reserved+k)/r.quantity*10000)-r.priority*500})}else arcs.push({from:2+supplies.length+j,to:sink,capacity:remaining,cost:0})});
 const result=flow(sink+1,0,sink,arcs,cap);const lines=result.lines.map(l=>({...details[l.tag],quantity:l.quantity}));return {total:result.sent,lines,unmet:needs.reduce((a,r)=>a+r.quantity-r.served-r.reserved,0)-result.sent,excluded,capacity:cap,weightKg:lines.reduce((a,l)=>a+l.quantity*l.weightKg,0),costPaise:lines.reduce((a,l)=>a+l.quantity*l.unitPrice,0),transportCo2Kg:lines.reduce((a,l)=>a+l.quantity*l.weightKg*l.km*.00015,0)};
}
export function transition(state:any,id:string,status:string){const plan=state.plans.find((p:any)=>p.id===id);if(!plan)throw new Error('Plan not found');if(plan.status===status)return false;if(plan.status!=='RESERVED')throw new Error('Reservation already settled');for(const line of plan.result.lines){const s=state.stock.find((s:any)=>s.id===line.stockId),r=state.requests.find((r:any)=>r.id===line.requestId);s.reserved-=line.quantity;r.reserved-=line.quantity;if(status==='DELIVERED')r.served+=line.quantity;else s.available+=line.quantity;if(s.reserved<0||r.reserved<0)throw new Error('Reservation integrity failure')}plan.status=status;return true}
export function reserve(state:any,id:string,p:any,kind:string,now=Date.now()){
 const existing=state.plans.find((x:any)=>x.id===id);if(existing){if(JSON.stringify(existing.parameters)!==JSON.stringify(p))throw new Error('Idempotency key reused for another request');return existing}
 if(state.plans.length>=100)throw new Error('Demo limit: 100 plans');const result=allocate(state.stock,state.requests,p,kind,now);if(!result.total)throw new Error('No compatible stock can be reserved');for(const l of result.lines){const s=state.stock.find((s:any)=>s.id===l.stockId),r=state.requests.find((r:any)=>r.id===l.requestId);s.available-=l.quantity;s.reserved+=l.quantity;r.reserved+=l.quantity}const plan={id,status:'RESERVED',parameters:p,result,createdAt:new Date(now).toISOString()};state.plans.unshift(plan);return plan;
}
